#!/bin/bash
# update rpm package
yum -y update

# disable selinux 
sed -i 's/SELINUX=enforcing/SELINUX=disabled/' /etc/selinux/config
setenforce 0

# create centos user
useradd centos && mkdir -p /home/centos/.ssh
cat << 'EOF' >> /home/centos/.ssh/authorized_keys 
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDfziP6w0FDOTQgBhXSOWQmEVdhURJr/kJjtqwAff1qvow8Fq028JmNBpscvH6XsRoX23PWW0X4kzmy9cuidcUiAabiVUBDpBVq5aFvsZgYazy11Y4MABBRH0N8RibhZnfND4Qttztras1q74LNnKu5CkPWz9kyWRDpu78hAuEvsP/xn7OSaSkaAv0pvwicjFXGdCwwPdnM3UCH7pKJgIhiYfArxBS+Bkzr9unaksR+rniZnFgQDn9vbLDlLbGOBziF5o/a8U/ocv/sw0FmXQtvbciRZsLcJ4D/hsavlkwYcck+GLGZNGvcRwmREoANlUhoieP1K3lpD98B+KIw1qU3 centos@hk-aliyun-wangwang-waf
EOF
chown -R centos:centos /home/centos && chmod 700 /home/centos/.ssh && chmod 600 /home/centos/.ssh/authorized_keys 

# config sshd_config 
# disbale 
# cp /etc/ssh/sshd_config /etc/ssh/sshd_config_bak
# sed -i 's/#PubkeyAuthentication yes/PubkeyAuthentication yes/' /etc/ssh/sshd_config 
# sed -i 's/#Port 22/Port 21022/' /etc/ssh/sshd_config

# config sudoer 
# delete line
cat << 'EOF' >>  /etc/sudoers.d/90-cloud-init-users
# User rules for centos
centos ALL=(ALL) NOPASSWD:ALL

# User rules for centos
centos ALL=(ALL) NOPASSWD:ALL
EOF
    # # or 
    # sed -i '/centos  ALL=(ALL)       NOPASSWD:ALL/d' /etc/sudoers   
    # # add line at the end 
    # sed -i '$a centos  ALL=(ALL)       NOPASSWD:ALL' /etc/sudoers

# history cmd set 
cat << 'EOF' >> /etc/bashrc
export HISTFILE=/var/log/.history_log
export HISTSIZE=5000
export HISTTIMEFORMAT="%Y-%m-%d %H:%M:%S `who am i | awk '{print $1,$5}'` "
export HISTCONTROL=ignoredups 
EOF

source /etc/bashrc

# sys kernel conf
cat << 'EOF' > /etc/sysctl.conf 
vm.swappiness = 0
kernel.sysrq = 1
net.ipv4.neigh.default.gc_stale_time = 120
net.ipv4.conf.all.rp_filter = 0
net.ipv4.conf.default.rp_filter = 0
net.ipv4.conf.default.arp_announce = 2
net.ipv4.conf.lo.arp_announce = 2
net.ipv4.conf.all.arp_announce = 2
#net.ipv4.tcp_max_tw_buckets = 5000
#net.ipv4.tcp_syncookies = 1
#net.ipv4.tcp_max_syn_backlog = 1024
net.ipv4.tcp_synack_retries = 2
net.ipv4.tcp_slow_start_after_idle = 0
#fs.file-max = 999999
#net.ipv4.tcp_tw_reuse = 1
#net.ipv4.tcp_keepalive_time = 600
#net.ipv4.tcp_fin_timeout = 30
net.ipv4.tcp_max_tw_buckets = 5000
net.ipv4.ip_local_port_range = 1024 65000
net.ipv4.tcp_rmem = 10240 87380 12582912
net.ipv4.tcp_wmem = 10240 87380 12582912
net.core.netdev_max_backlog = 8096
net.core.rmem_default = 6291456
net.core.wmem_default = 6291456
net.core.rmem_max = 12582912
net.core.wmem_max = 12582912
net.ipv4.tcp_syncookies = 1
net.ipv4.tcp_max_syn_backlog = 8192
net.ipv4.tcp_tw_recycle = 1
#net.core.somaxconn=262114
net.core.somaxconn=65535
net.ipv4.tcp_max_orphans=262114
fs.file-max = 999999
net.ipv4.tcp_tw_reuse = 1
net.ipv4.tcp_keepalive_time = 600
net.ipv4.tcp_fin_timeout = 30
EOF

sysctl -p

cat  << 'EOF' >> /etc/security/limits.conf 
root soft nofile 65535
root hard nofile 65535
* soft nofile 65535
* hard nofile 65535
EOF

# iptables set 
cat << 'EOF' >> /tmp/iptables.sh
cat /tmp/11.sh
# Generated by iptables-save v1.4.21 on Wed Dec  8 23:58:24 2021
*filter
:INPUT ACCEPT [0:0]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [882161:321737320]
-A INPUT -p icmp -j REJECT --reject-with icmp-port-unreachable
-A INPUT -p tcp -m multiport --dports 22,80,443 -m state --state NEW,ESTABLISHED -j ACCEPT
-A INPUT -s 127.0.0.1/32 -d 127.0.0.1/32 -j ACCEPT
-A INPUT -p udp -m udp --sport 53 -j ACCEPT
-A INPUT -p udp -m udp --dport 53 -j ACCEPT
-A INPUT -m state --state RELATED,ESTABLISHED -j ACCEPT
-A INPUT -j DROP
COMMIT
# Completed on Wed Dec  8 23:58:24 2021
EOF
iptables-restore /tmp/iptables.sh




